### DISCUSSION TITLE
Bicep workflow

### DISCUSSION THREAD

**Discussion by dazinator** [microsoft/PSRule#1397] [Q&A]
I have a question over how this tool should be used in a bicep workflow.

1. Do we need to first build the bicep template to an ARM json template using the bicep cli?
2.  The az devops task to do the analysis is mentioned in the readme like so:

```
 # STEP 4: Run analysis against exported data
  - task: ps-rule-assert@2
    displayName: Analyze Azure template files
    inputs:
      modules: 'PSRule.Rules.Azure'
```

What does it mean by "exported data"? In my case I have a bicep template not in the root of the repository. Do I have to point this analysis step to the path of the bicep template to be analysed (is there a parameter for that?) Or do I point it to the ARM output produced via `az bicep build` ? 

Many Thanks
