### DISCUSSION TITLE
Rule not finding field in JSON Configuration

### DISCUSSION THREAD

**Discussion by sapritchard** [microsoft/PSRule#2786] [Q&A] [answered]
Hi, I'm just starting to work with PSRule in an effort to migrate from an internally built infrastructure testing platform that uses Pester. Our infrastructure is defined in JSON configuration files with a custom schema. Our configurations will remain as they are I'll just be moving to PSRule rule modules for configuration validation and eventually configuration drift detection.

My problem that I'm struggling to work out and I'm sure it's just me understanding at this stage, I do read the docs (thank you for excellent documentation), is that if I collect a configuration file using a `$config = Get-ChildItem -Path 'C:\file_path\' -Include 'datacenter.json' -Recurse` then pipe that into my test rule `$config | Assert-PSRule -Path 'C:\file_path\test.datacenter.Rule.yaml'`. I get a failure of:

```
| REASON:
    | - Path .Type.datacenter.Name: The field '.Type.datacenter.Name' does not exist.
```

But when running supplying the config file as the value to the `-InputPath` parameter all works fine and I can pass or deliberately fail based on the values in the config file.

Can I please get any guidance on what I may be doing wrong, collecting files will be key as part of the effort and building out the validation pipeline in jenkins.

Config schema example:
```json
{
"Type": {
		"datacenter": {
			"Name": [
				"DEV_LAB"
			]
		}
	}
}
```

Rule:
```yaml
# Synopsis: Name array contains at least one member.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: datacenter.name.member.count
  ref: VAF-011
spec:
  condition:
    field: Type.datacenter.Name
    greaterOrEquals: 1
```
