### DISCUSSION TITLE
Module Config

### DISCUSSION THREAD

**Discussion by sapritchard** [microsoft/PSRule#2848] [Q&A] [answered]
I'm looking to control the behavior of the banner and footer through a yaml config (config.Rule.yaml) located within the module directory structure, but any changes I make don't reflect when running Assert-PSRule. 
I do remove and re-import the module after each change and I'm using the doco - https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Options/#outputbanner

```yaml
---
# Synopsis: Module configuration for test.config.common.Rules.
apiVersion: github.com/microsoft/PSRule/v1
kind: ModuleConfig
metadata:
  name: test.config.common.Rules
spec:
  binding:
    targetName:
      - ResourceName
      - Host
    targetType:
      - ResourceType
  rule:
    baseline: test.config.common.Rules
  output:
    banner: Minimal
    footer: RuleCount
```

Any changes to either banner or footer still results in the default output. It's not a big drama and is more just to keep the output as minimal for users.
