### DISCUSSION TITLE
Conventions

### DISCUSSION THREAD

**Discussion by sapritchard** [microsoft/PSRule#2884] [Q&A] [answered]
I've written a convention as part of a module and it resides within the rules directory `convention.Rule.ps1`:
```text
\---config.datacenter.Rules
    |   config.datacenter.Rules.psd1
    |
    +---en
    |       .gitkeep
    |       about_config.datacenter.Rules.help.txt
    |
    \---rules
            .gitkeep
            baseline.Rule.yaml
            config.Rule.yaml
            convention.Rule.ps1
            datacenter.Rule.ps1
```

I've included the convention in the module configuration file `config.Rule.yaml`
```yaml
---
# Synopsis: Module configuration for config.datacenter.Rules.
apiVersion: github.com/microsoft/PSRule/v1
kind: ModuleConfig
metadata:
  name: config.datacenter.Rules
spec:
  binding:
    targetName:
      - ResourceName
      - Host
    targetType:
      - ResourceType
    convention:
    include:
      - match.name.key
  rule:
    baseline: config.datacenter.Rules
```

When I load the module and then run `Assert-PSRule -Module 'config.datacenter.Rules' -InputPath 'C:\_Data\config.datacenter.Rules\test_files\datacenter.version_3_0_0.json'
It fails to execute the convention but when I include the `-Convention` parameter as part of the call
`Assert-PSRule -Module 'config.datacenter.Rules' -InputPath 'C:\_Data\config.datacenter.Rules\test_files\datacenter.version_3_0_0.json -Convention 'match.name.key' it runs as expected.

From reading the docs I though including in the module config file would negate the need to include the `-Convention` parameter. Just wanted to see if my understanding is correct and I do need to include the parameter or is my module config wrong?

**Comment by BernieWhite** [comment, marked as answer]
Hi @sapritchard, thanks for the question.

The config looks good excepting the indent on the `convention` key as it should be a peer of `binding` or `rule`; child of `spec`. Should be like:

```yaml
---
# Synopsis: Module configuration for config.datacenter.Rules.
apiVersion: github.com/microsoft/PSRule/v1
kind: ModuleConfig
metadata:
  name: config.datacenter.Rules
spec:
  binding:
    targetName:
      - ResourceName
      - Host
    targetType:
      - ResourceType
  convention:
    include:
      - match.name.key
  rule:
    baseline: config.datacenter.Rules
```

See https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Conventions/#using-within-modules

If editing within VSCode, the extension should help by validating against the schema.

PSRule v2 see: https://marketplace.visualstudio.com/items?itemName=bewhite.psrule-vscode

Alternatively, you could manually validate against the schema if you are using different tooling. The schema is here: https://github.com/microsoft/PSRule/blob/release/v2.9.x/schemas/PSRule-language.schema.json
