### DISCUSSION TITLE
PSRule v2 pre-release

### DISCUSSION THREAD

**Discussion by BernieWhite** [microsoft/PSRule#966] [Announcements]
---
**Update: PSRule v2 is now available**
--

The next version of PSRule is on it's way. 🎉 

We'd like to take the time to ask for any additional feedback as we finalize the initial v2 release.

---

See [upgrade notes](https://microsoft.github.io/PSRule/v2/upgrade-notes/) for key points around breaking changes in v2.

---

If you like to try it out you can:

**Try it out in GitHub Actions**

By referencing `microsoft/ps-rule@main`, setting `prerelease` and `version`.

For example:

```yaml
- name: Run PSRule analysis
  uses: microsoft/ps-rule@main
  with:
    prerelease: true
    version: '2.0.0-B2203033'
```

**Try it out locally**

Install the pre-release module [see details](https://microsoft.github.io/PSRule/v2/install-instructions/#getting-the-modules).

For example:

```powershell
Update-Module -Name 'PSRule' -Repository PSGallery -Scope CurrentUser -AllowPrerelease;
```

---

Thanks to everyone who as already logged issues or discussion in the repository 👍 .
