### ISSUE TITLE
Configuration for YAML/ JSON based rules

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#1016]
Currently PowerShell-based rules can use configuration values from options.

This is currently not supported for YAML/ JSON rules, we should add this feature.

Related to discussion Azure/PSRule.Rules.Azure#1314

May be able to work into: #1033

**Comment by ArmaanMcleod** [comment]
@BernieWhite I can probably help with this one. Was thinking `configuration` could be another comparison property like `field`, `name`, `type`, `source` we could introduce.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Thanks. Agreed.

**Comment by ArmaanMcleod** [comment]
@BernieWhite If we had a configuration defined like below:

```yaml
configuration:
  allowedBusinessUnits:
  - 'IT Operations'
  - 'Finance'
  - 'HR'
```

And a YAML rule

```yaml
---
# Synopsis: A YAML rule for testing.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: RuleYamlTagConfig
spec:
  condition:
    allOf:
    - field: 'tags.businessUnit'
      exists: true
    - field: 'tags.businessUnit'
      in:
        configuration: 'allowedBusinessUnits'
```

How would this work with the existing schema? Since `in` would expect an array of values to compare against. 

Or would we need to convert this to an array of values

```yaml
- field: 'tags.businessUnit'
  in:
     - configuration: 'allowedBusinessUnits'
```

**Comment by BernieWhite** [comment]
@ArmaanMcleod I was thinking something like this:

```yaml
- field: 'tags.businessUnit'
  in:
    $:
      configuration: 'allowedBusinessUnits'
```

It should be easy to update the schema to support all the advanced use cases for complex function support through a `$` object.
