### ISSUE TITLE
Configure columns for CSV output

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#1165]
Currently the CSV output is fixed, providing some additional options to configure the columns include in the output would be useful for some scenarios.

Such as adding a description or online link column.

An example might allow the following configuration:

```yaml
output:
  csvDetailedColumns:
  - RuleName
  - TargetName
  - TargetType
  - Outcome
  - OutcomeReason
  - Synopsis
  - Recommendation
```
