### ISSUE TITLE
Support for tags with multi-values

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#1272]
**Description of the issue**

When specifying tags, only a single string value works. Using a string array, PSRule errors.

**To Reproduce**

Steps to reproduce the issue:

```yaml
# Synopsis: Use Azure AD identities instead of using the registry admin user.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.ACR.AdminUser
  ref: AZR-000005
  tags:
    release: 'GA'
    ruleSet: '2020_06'
    Azure.WAF/pillar: 'Security'
    Azure.ASB.v3/control: [ 'IM-1', 'IM-3', 'PA-1', 'PA-7' ]
spec:
  type:
  - Microsoft.ContainerRegistry/registries
  condition:
    field: Properties.adminUserEnabled
    hasDefault: false
```

**Expected behaviour**

PSRule should be able to handle of tags have multi-string values.

**Error output**

```text
ERROR: (Line: 21, Col: 27, Idx: 437) - (Line: 21, Col: 27, Idx: 437): No node deserializer was able to deserialize the node into type System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
```

**Module in use and version:**

- Module: PSRule
- Version: **2.4.0**
