### ISSUE TITLE
Add help properties to rules from YAML/ JSON resources

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#1386]
Currently some help properties can only be set with markdown documentation. These properties include:

- The rule display name.
- The rule description.
- A link to online documentation.
- The rule recommendation.

Adding these properties provides a quick way to return some detailed information for the rule without having to add markdown documentation.

We should add support for these properties, for example:

```yaml
---
# Synopsis: Storage Accounts should only accept explicitly allowed traffic.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: Azure.Storage.Firewall
  ref: AZR-000202
  tags:
    release: 'GA'
    ruleSet: '2021_09'
  displayName: 'Configure Azure Storage firewall'
  description: By default, storage accounts accept connections from clients on any network. To limit access to selected networks, you must first change the default action.
  link: https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Storage.Firewall/
spec:
  recommend: 'Consider configuring storage firewall to restrict network access to permitted clients only. Also consider enforcing this setting using Azure Policy.'
  type:
  - Microsoft.Storage/storageAccounts
  with:
  - Azure.Usage.NotCloudShell
  condition:
    field: properties.networkAcls.defaultAction
    equals: deny
```

**Note:** These properties are not localized. To set localized properties use markdown documentation.

---

This is related to Azure/PSRule.Rules.Azure#1959
