### ISSUE TITLE
Add support for baseline groups

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#1541]
Add support for baseline groups as defined in #1524.

---

Provide an option to configure a baseline group, which is like an friendly name for the baseline but one that can be set within options.

For example:

```yaml
baseline:
  group:
    recommended: PSRule.Rules.Azure\Azure.Default
    preview: PSRule.Rules.Azure\Azure.Preview
```

```yaml
# Analyze Azure resources using PSRule for Azure
- name: Analyze Azure template files
  uses: microsoft/ps-rule@v2.8.1
  with:
    modules: 'PSRule.Rules.Azure'
    baseline: '@recommended'
```
