### ISSUE TITLE
Investigate Input.IgnoreObjectSource bug

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#1753]
**Description of the issue**

The option `Input.IgnoreObjectSource` is not working correcting with the following options:

```yaml
input:
  # By default, objects read from file using inputPath will be skipped if the file path has been ignored.
  # When set to true, additionally objects with a source path that has been ignored will be skipped.
  ignoreObjectSource: true
  
  # By default, PSRule will process all files within an input path.
  ignoreUnchangedPath: true

  pathIgnore:
    # Ignore other files in the repository.
    - '**'

    # Include deployment files.
    - '!deployments/**/*.bicepparam'
    - '!deployments/**/main.bicep'
```

**Expected behaviour**

All files should be ignored except `*.bicepparam` and `main.bicep` files.

**Module in use and version:**

- Module: PSRule
- Version: **2.9.0**

**Additional context**

Related to Azure/PSRule.Rules.Azure#2678
