### ISSUE TITLE
Baseline created by data export not found

### ISSUE THREAD

**Issue by Lucas-c-B** [microsoft/PSRule#1833]
**Description of the issue**

After exporting the policy assignment data of my environment, the baseline is not found when using  ```Assert-PSRule``` or  ```Get-PSRuleBaseline```. However, when I run ```Get-PSRuleBaseline .```, the baseline is found, confirming that it's been generated.

**To Reproduce**

Steps to reproduce the issue:

I run the following commands from the root of my repository:

```powershell
Set-AzContext -Subscription $subscriptionName
$export = Export-AzPolicyAssignmentData
Export-AzPolicyAssignmentRuleData -AssignmentFile $export.FullName
Assert-PSRule -Format File -InputPath '.' -Module 'PSRule.Rules.Azure' -Baseline 'Azure.PolicyBaseline.All'
```

ps-rule.yaml
```yaml
requires:
  # Require a minimum of PSRule for Azure v1.34.2
  PSRule.Rules.Azure: ">=1.34.2"

binding:
  targetType:
    - "resourceType"
    - "type"

input:
  format: "File"
  pathIgnore:
    - "*"
    - "**/*"
    - "!**.bicepparam"

output:
  culture:
    - en-US

rule:
  includeLocal: true

configuration:
  AZURE_BICEP_FILE_EXPANSION: true
  AZURE_PARAMETER_FILE_EXPANSION: true
```

export (baseline part)
```json
{
    // Synopsis: Generated automatically when exporting Azure Policy rules.
    "apiVersion": "github.com/microsoft/PSRule/v1",
    "kind": "Baseline",
    "metadata": {
      "name": "Azure.PolicyBaseline.All"
    },
    "spec": {
      "rule": {
        "include": [
          "Azure.Policy.56b22bf44513",
          "Azure.Policy.cd170d7655f5",
          "Azure.Policy.0c5824aa6e83",
          "Azure.Policy.32a9768b3eef",
          "Azure.Policy.af9bfd8f877d",
          "Azure.Policy.86c8759e7b98",
          "Azure.Policy.c0831b099d37",
          "Azure.Policy.5546ab5e220e",
          "Azure.Policy.c64c5d04b896",
          "Azure.Policy.59efb9708d23",
          "Azure.Policy.d3c2c8d3bbf2",
          "Azure.Policy.e5da446570a8",
          "PSRule.Rules.Azure\\Azure.AKS.UseRBAC",
          "PSRule.Rules.Azure\\Azure.AKS.AzurePolicyAddOn"
        ]
      }
    }
  }
```

**Expected behaviour**

The baseline should be found without providing a path to the  ```Get-PSRuleBaseline``` cmdlet, so it can be used by ```Assert-PSRule```.

**Error output**

```text
PSR0004: The specified Baseline resource 'Azure.PolicyBaseline.All' is not known.
```

**Module in use and version:**

- Module: PSRule
- Version: **2.9.0**

- Module: PSRule.Rules.Azure
- Version: **1.34.2**

Captured output from `$PSVersionTable`:

```text
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**

When exporting data from another environment with the same commands, the baseline does get found and ```Assert-PSRule``` works as expected
