### ISSUE TITLE
Path filtering of ignored files includes prefixed files.

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#2624]
**Description of the issue**

In the following configuration, a file named `abc.csproj` should be ignored but it no because of the previous exclusion for `!**/*.cs` because `.cs` matches all part of the file name before.

```yaml
input:
  fileObjects: true
  pathIgnore:
    - '**'
    - '!**/*.cs'
    - '!**/*.ps1'
    - '!**/*.psd1'
    - '!**/*.psm1'
    - '*.Designer.cs'
```

**Module in use and version:**

- Module: PSRule
- Version: **3.0.0**
