### ISSUE TITLE
[DOCS] Processing changed files does not include full git history

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#2749]
### URL

https://microsoft.github.io/PSRule/v3/creating-your-pipeline/

### How could the documentation be improved?

To compare changed files full git history must be fetched. Both GitHub Actions and Azure Pipelines to a shallow fetch be default.

The instructions and examples need to be updated to include this as a required step for processing changes files only to work.

GitHub Actions:

```yaml
- uses: actions/checkout@v4
  with:
    fetch-depth: 0
```

Azure Pipelines

```yaml
  # Checkout the repository
  - checkout: self
    fetchDepth: 0
```

### Additional context

Discussed here: https://github.com/microsoft/PSRule/issues/1465#issuecomment-2631360477
