### ISSUE TITLE
Add qualified target names

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#395]
In the scenario where two similarly named objects exist, `TargetName` will return the same name for both objects when bound to `metadata.name`.

One object is a `Deployment` the other is a `Service`.

In this scenario we should have an option to qualify the name and prefix with the type.
i.e. `Deployment/azure-vote-back` and `Service/azure-vote-back`.

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
```
