### ISSUE TITLE
Add support for YAML based rule expressions

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#603]
Currently rules can only be defined in PowerShell script blocks. In many cases these rules could be represented in a YAML expression.

While complex logic would probably still require PowerShell script blocks, many of the assertion helper methods available through `$Assert` could be represented as a YAML expression tree.

For example:

```yaml

---
# Synopsis: This is an example YAML rule expression
apiVersion: github.com/Microsoft/PSRule/v1
kind: Rule
metadata:
  name: YamlRule1
spec:
  selector:
  - targetObject:
      allOf:
      - field: 'Name'
        hasValue: 'TestObject1'
```
