### ISSUE TITLE
Add strong apiVersion to resource types

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#647]
For YAML resources such as baselines and module configurations future major changes to the schema of these is not accommodated.

Adding an additional `apiVersion` property to each resource will allow future versioning. i.e.

```yaml
---
# Synopsis: This is an example baseline
apiVersion: github.com/Microsoft/PSRule/v1
kind: Baseline
metadata:
  name: Baseline1
spec: { }
```

This `apiVersion` property should be optional prior to PSRule v2 and mandatory > v2. This will be a breaking change for v2.

Related to #648
