### ISSUE TITLE
Require strong apiVersion for resource types

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#648]
Require strong `apiVersion` on PSRule resources.

```yaml
---
# Synopsis: This is an example baseline
apiVersion: github.com/Microsoft/PSRule/v1
kind: Baseline
metadata:
  name: Baseline1
spec: { }
```
