### ISSUE TITLE
Expected DocumentEnd got SequenceEnd

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#698]
**Description of the issue**

Issue parsing YAML files starting with sequence in file instead of an object or `---` separated objects.

**To Reproduce**

Using a file with the following contents as an input to `-InputPath` will error.

```yaml
- name: Getting started
  href: Getting-started/
  topicHref: Getting-started.md
- name: Azure
  href: Azure/
  topicHref: Azure.md
- name: Templates
  href: Templates/
```

**Expected behaviour**

Add support for items directly within YAML file.

**Error output**

```text
OperationStopped: C:\Users\<removed>\Documents\PowerShell\Modules\PSRule\1.3.0\PSRule.psm1:611
Line |
 611 |              throw $_.Exception.GetBaseException();
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Expected 'DocumentEnd', got 'SequenceStart' (at Line: 1, Col: 1, Idx: 0).
```

**Module in use and version:**

- Module: PSRule
- Version: **1.3.0-B2104030**

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
