### ISSUE TITLE
Configuration array deserializes as dictionary from YAML options

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#779]
**Description of the issue**

When configuring configuration options from YAML, array objects are deserialized as a dictionary instead of `PSObject[]`.

**To Reproduce**

Steps to reproduce the issue:

```yaml
configuration:
  AZURE_AKS_ADDITIONAL_REGION_AVAILABILITY_ZONE_LIST:
  - location: 'Australia Southeast'
    zones:
      - "1"
      - "2"
      - "3"
  - location: 'Norway East'
    zones:
      - "1"
      - "2"
      - "3"

```

```powershell
$o = New-PSRuleOption .\tests\PSRule.Rules.Azure.Tests\ps-rule-options.yaml
$o.Configuration['AZURE_AKS_ADDITIONAL_REGION_AVAILABILITY_ZONE_LIST']
```

returns:

```text
Key      Value
---      -----
location Australia Southeast
zones    {1, 2, 3}
location Norway East
zones    {1, 2, 3}
```

**Expected behaviour**

Object should deserialize as an array of `PSObject` instead.

**Module in use and version:**

- Module: PSRule
- Version: **1.6.0**

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**

[See discussion](https://github.com/Azure/PSRule.Rules.Azure/pull/906#discussion_r695379480).
