### ISSUE TITLE
Add support for rule aliases

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#792]
Current when a rule is renamed it is a breaking change because existing suppressions or rule exclusions are no honoured with the new name.

Also depends on references would also break.

Adding the ability to alias rules would allow rules to be renamed without a breaking change.

Also warning on using a rule through an alias would be a good idea.

Related to Azure/PSRule.Rules.Azure#933

Defining a rule alias may look like:

```powershell
Rule 'Rule1' -Alias 'Rule1AlternativeName','RuleB' {
    # implementation
}
```

```yaml
---
# Synopsis: A rule with an alias.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: 'YAML.RuleWithAlias1'
  alias:
  - 'AlternativeName'
spec:
  condition:
    field: name
    exists: true
```
