### ISSUE TITLE
Add support for suppression groups

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#793]
Currently when suppressing rules each suppression is done on a 1:1 basis.

To provide greater flexibility it would be helpful to provide an ability to select several objects for suppression based on a selector.

```yaml
---
# Synopsis: A test suppression group
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressWithTestType
spec:
  rule:
    name:
    - 'rule1'
  if:
    type: '.'
    startsWith: 'Test'
```

Before this is possible, we need to improve output logging to show suppression so suppressed objects can be tracked.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Quick question about:

```yaml
---
# Synopsis: A test suppression group
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressWithTestType
spec:
  rule:
    name:
    - 'rule1'
  if:
    type: '.'
    startsWith: 'Test'
```

How would this account for rule name and target name filtering similar to the current suppression capability?

Or is `name` really `targetName`, where we filter just the target names, which would map to this rule suppression rule class: https://github.com/microsoft/PSRule/blob/main/src/PSRule/Configuration/SuppressionRule.cs. 

If thats the case I think it would make more sense to do:

```yaml
rule:
  targetName:
  - 'rule1'
```

But this still makes me think another layer is needed for rule name:

```yaml
rule:
  MyRule.DoSomething:
    targetName:
    - TestObject1
    - TestObject3
```

Which matches up wth the existing suppression format: https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Options/#suppression

Let me know if I'm missing something.

**Comment by BernieWhite** [comment]
@ArmaanMcleod The existing support for suppression would still exist and if you wanted to create a suppression group to provide the same functionality you would do as you suggested using the `name: '.'` which is bound to `TargetName`.

Suppress an object by name using name comparison property (https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Expressions/#name):

```yaml
---
# Synopsis: A test suppression group
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressWithTestType
spec:
  rule:
    name:
    - 'rule1'
  if:
    name: '.'
    in:
    - 'TestObject1'
    - 'TestObject2'
```

You could also do type based suppression which isn't currently possible using options (https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Expressions/#type).

In terms of name in the example:

```yaml
spec:
  rule:
    name:
    - 'rule1'
```

I was referring to the name of the rule, which would be an array of rule names. i.e. suppress objects matching `if` condition for these rules by name.

We could just simplify this by just doing:

```yaml
spec:
  rule:
  - 'rule1'
```

If that makes sense.

**Comment by BernieWhite** [comment]
@ArmaanMcleod In an example case suppose a customer wanted to suppress [Azure.Storage.UseReplication](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Storage.UseReplication/) for any storage accounts that are non-production.

```yaml
---
# Synopsis: A test suppression group
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressNonProductionStorageGRS
spec:
  rule:
  - 'Azure.Storage.UseReplication'
  if:
    field: 'tags.env'
    in:
    - 'dev'
    - 'test'
```

That could also be expanded to [Azure.Storage.SoftDelete](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Storage.SoftDelete/).

```yaml
---
# Synopsis: A test suppression group
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressNonProductionStorageGRS
spec:
  rule:
  - 'Azure.Storage.UseReplication'
  - 'Azure.Storage.SoftDelete'
  if:
    field: 'tags.env'
    in:
    - 'dev'
    - 'test'
```
