### ISSUE TITLE
Migrate default baseline to module configuration

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#809]
Currently a default baseline can be configured by editing the module manifest.

```powershell
@{
  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData = @{
      PSData = @{
          # Tags applied to this module. These help with module discovery in online galleries.
          Tags = @('PSRule-rules')
      }
      PSRule = @{
          Baseline = 'Enterprise.Default'
      }
  }
}
```

Adding a PSRule property in the manifest is problematic because the `Update-ModuleManifest` cmdlet reformats this.

Module configuration support was added later which provides an alternative mechanism to configure the default baseline.

For example:

```yaml
---
# Synopsis: Example module configuration for Enterprise.Rules module
apiVersion: github.com/microsoft/PSRule/v1
kind: ModuleConfig
metadata:
  name: Enterprise.Rules
spec:
  rule:
    baseline: 'Enterprise.Default'
```

If default baseline in both module manifest and module configuration are set, Module configuration should take priority.
