### ISSUE TITLE
Stable rule identifier

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#881]
Currently renaming a rule is a breaking change (See rule alias #792).

Additional SARIF (#878) recommends using a rule identifier that is "stable, opaque" providing the following as reasons:

> It shouldn't change over time so that build scripts that disable a particular rule never break. It should be opaque (as opposed to being a human-readable string) for ease of web lookup and to avoid language difficulties.

https://github.com/microsoft/sarif-tutorials/blob/main/docs/2-Basics.md#rule-identifier

Defining a rule ref identifier may look like:

```powershell
Rule 'Rule1' -Ref 'RZ.0001' {
    # implementation
}
```

```yaml
---
# Synopsis: A rule with a rule ref identifier.
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: 'YAML.RuleWithAlias1'
  ref: 'RZ.0002'
spec:
  condition:
    field: name
    exists: true
```
