### ISSUE TITLE
Add expression support for type based assertions

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#908]
Currently the following assertion methods doesn't have an equivalent expression in YAML/ JSON.

- IsArray
- IsBoolean
- IsDateTime
- IsInteger
- IsNumeric

We should add support for these.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Similar to expressions, should we give the ability to set `convert` to convert values?

Wondering how this would work with expressions:

```yaml
---
# Synopsis: Test isBoolean
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: YamlIsBooleanTrue
spec:
  if:
    field: 'Value'
    isBoolean: true
```

or do we just not convert by default, and `"true"` would always be `false`.

**Comment by BernieWhite** [comment]
@ArmaanMcleod Let's keep the behaviour like assertions. Specifically don't convert by default, but provide a parameter to opt-in to conversion for the assertions that have that currently exposed.

For the assertions that do not have that option, don't convert.

Some limited expressions expose additional properties such as `setOf` [ref](https://microsoft.github.io/PSRule/v2/concepts/PSRule/en-US/about_PSRule_Expressions/#setof). I think we should expose an additional `convert` bool property that can be `true`/ `false` to convert the type.

```yaml
---
# Synopsis: Test isBoolean
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: YamlIsBooleanTrue
spec:
  if:
    field: 'Value'
    isBoolean: true
    convert: true
```
