### ISSUE TITLE
Empty suppression group rules property applies to no rules

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#931]
**Description of the issue**

When you define a suppression group, and explicitly `rule` property without any members the suppression group is effectively ignored. 

**To Reproduce**

Steps to reproduce the issue:

```yaml
---
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Local.IgnoreKeyVaultTests
spec:
  rule: []
  if:
    name: '.'
    in:
    - 'kv-test-001'
```

**Expected behaviour**

If a specific set of rules is not defined, it should apply to all rules.

**Module in use and version:**

- Module: PSRule
- Version: **v2.0.0-B2201117**

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
