### ISSUE TITLE
Add a source expression property

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/PSRule#933]
Currently the expression properties `field`, `name`, or `type` can be used. In PowerShell the source file for the object can be referenced using `$PSRule.Source`.

For example:

```powershell
# Synopsis: Policy exemptions must be stored under designated paths for review.
Rule 'Org.Azure.Policy.Path' -Type 'Microsoft.Authorization/policyExemptions' {
    $Assert.WithinPath($PSRule.Source['Parameter'], '.', @(
        'deployments/policy/'
    ));
}
```

Currently `$PSRule.Source` is not available within expressions, neither is an equivalent of `$Assert.WithinPath`.

It would be helpful to provide both options to allow suppression groups to exclude objects based on their origin path.

For example:

```yaml
---
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Local.IgnoreACRTests
spec:
  if:
    source: 'file'
    withinPath: 'modules/**/*.tests.bicep'
```

**Comment by ArmaanMcleod** [comment]
@BernieWhite Similar to `WithinPath` assertion, should this also support giving an array of paths?

**Comment by BernieWhite** [comment]
@ArmaanMcleod Yep. Sounds good. Not sure on how `notWithinPath` would be used, but it would be easy to add.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Should we include warnings for this, similar to what we do for rules?

**Comment by BernieWhite** [comment]
@ArmaanMcleod I don't think the implementation for souce and withinpath needs to be suppression group specific, it should also work for rules or selectors. As such the message probably doesn't need to be specific. I.e. if the condition matches then the object is suppressed.

**Comment by ArmaanMcleod** [comment]
@BernieWhite Yeah don't think it should be suppression group specific as well, Selectors like below should work as well:

```yaml
apiVersion: github.com/microsoft/PSRule/v1
kind: Selector
metadata:
  name: YamlSourceWithinPath
spec:
  if:
    source: 'Template'
    withinPath:
      - "deployments/path/"
```

I can probably just keep the warning message like `Object {0} with source {1} was suppressed`.
